export const GamesTypes = {
  // Sync

  SET_GAMES: 'Games/SET_GAMES',
  FETCH_GAMES_REQUEST: 'Games/FETCH_GAMES_REQUEST',
  FETCH_GAMES_SUCCESS: 'Games/FETCH_GAMES_SUCCESS',
  FETCH_GAMES_FAILURE: 'Games/FETCH_GAMES_FAILURE',

  // Async
  FETCH_GAMES_ASYNC: 'Games/FETCH_GAMES_ASYNC',
};
